In [622]:
import numpy as np  #1

a = np.array([1 , 2 , 3 , 4 , 5 ]) 
a[::-1]

array([5, 4, 3, 2, 1])

In [623]:
#2

a[::2] * 10

array([10, 30, 50])

In [624]:
#3

a[::2] ** 2

array([ 1,  9, 25], dtype=int32)

In [625]:
#4

ex4 = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9]) 
ex4.reshape((3,3))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [626]:
#5

c = np.array([[1,2,3],[4,5,6]])
c[ :, 1]

array([2, 5])

In [627]:
#6

N = 9
def tab(n) :
    ex6 = np.arange(1, n + 1).reshape(3, 3)
    ex6_2 = ex6 * 10
    return np.concatenate((ex6, ex6_2), axis=1)
    

tab(N)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60],
       [ 7,  8,  9, 70, 80, 90]])

In [628]:
#7

def tab_ones(n) : 
    ex7 = np.ones((n,n))
    ex7[1:n - 1, 1:n-1] += 1
    return ex7

tab_ones(N)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 2., 2., 2., 2., 2., 2., 2., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [629]:
#8

ex8 = np.arange(1,10).reshape((3,3))
ex8_2 = np.array([0,2,3])
ex8 += ex8_2
ex8


array([[ 1,  4,  6],
       [ 4,  7,  9],
       [ 7, 10, 12]])

In [630]:
#9

a = np.array([
 [1, 2, 3, 4, 5],
 [6,7,8,9,10],
 [11,12,13,14,15]])

b = np.array([[0,1], [0,3], [1,4]]) 
ex9 = np.take(a,b, axis=1)
ex9 = np.transpose(ex9,(1,0,2))
ex9


array([[[ 1,  2],
        [ 6,  7],
        [11, 12]],

       [[ 1,  4],
        [ 6,  9],
        [11, 14]],

       [[ 2,  5],
        [ 7, 10],
        [12, 15]]])

In [631]:
#10

ex10 = np.random.randint(20,size=20)
print("Tableau de base : \n",ex10)
ex10[ex10 > 10] = 20
print("\nTableau après transformation des valeurs supérieure à 10 en 20 : \n",ex10)

Tableau de base : 
 [ 0 14 19  9  3 14 16  1  5 13 14  4 15  5  0  5 19  9 12  7]

Tableau après transformation des valeurs supérieure à 10 en 20 : 
 [ 0 20 20  9  3 20 20  1  5 20 20  4 20  5  0  5 20  9 20  7]


In [632]:
#11 

ex11 = np.random.randint(10,size=10)
print("Tableau :\n", ex11)
if np.all(ex11 != 0) :
    print("Il n'y a aucune valeur nulle")
else :
    print("Il y a au moins une valeur nulle")

Tableau :
 [0 7 7 7 1 4 8 4 3 3]
Il y a au moins une valeur nulle


In [633]:
#12

ex12 = np.zeros(5)
#ex12 = np.array([0.1,0,0,1,0])
print("Tableau :\n", ex12)
if np.any(ex12 != 0) :
    print("Il y a au moins une valeur non nulle")
else :
    print("Il y a que des valeurs nulle")
    

Tableau :
 [0. 0. 0. 0. 0.]
Il y a que des valeurs nulle


In [634]:
#13

ex13 = np.array([1, 2, 3, 4])
np.repeat(ex13, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [635]:
#14

ex14 = np.array([[ 0, 10, 20, 30],
 [ 40, 50, 60, 70],
 [ 80, 90, 100, 110]]) 

ex14 = ex14[1:, [2, 0, 1]]
ex14[1] = ex14[1] // 10
ex14

array([[60, 40, 50],
       [10,  8,  9]])

In [636]:
#15

ex15 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ex15 = np.repeat(ex15, 2, axis=1)
np.repeat(ex15,2, axis=0)

array([[1, 1, 2, 2, 3, 3],
       [1, 1, 2, 2, 3, 3],
       [4, 4, 5, 5, 6, 6],
       [4, 4, 5, 5, 6, 6],
       [7, 7, 8, 8, 9, 9],
       [7, 7, 8, 8, 9, 9]])

In [637]:
#16

data = np.array([[1, 1275], [1, 1441], [1, 1494], [1, 1593],
              [2, 1679], [2, 1533], [2, 1686],
              [3, 1559], [3, 1219], [3, 1455],
              [4, 1605], [4, 1468], [4, 1692], [4, 1613]])

values = data[:,1]
data2 = np.ravel(data[:, [0]])
a, indices = np.unique(data2, return_index=True)
np.split(values, indices[1:])

[array([1275, 1441, 1494, 1593]),
 array([1679, 1533, 1686]),
 array([1559, 1219, 1455]),
 array([1605, 1468, 1692, 1613])]

In [638]:
#17

data = np.array([[1, 1275],[4, 1468], [4, 1692],[2, 1533],
                 [2, 1686], [1, 1441], [1, 1494], [1, 1593],
                 [3, 1219], [3, 1455],[3, 1559], 
                 [2, 1679], [4, 1605],  [4, 1613]])

a = np.argsort(data[:,0])
data = data[a, :]

values = data[:,1]
data2 = np.ravel(data[:, [0]])
a, indices = np.unique(data2, return_index=True)
np.split(values, indices[1:])


[array([1275, 1441, 1494, 1593]),
 array([1533, 1686, 1679]),
 array([1219, 1455, 1559]),
 array([1468, 1692, 1605, 1613])]

In [639]:
#18

ex18 = np.array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11]])

ex18[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [640]:
#19

ex19 = np.indices((10, 10))[0]
ex19[ex19 <= 5].reshape(6,-1)[2::3,2::3]


array([[2, 2, 2],
       [5, 5, 5]])

In [641]:
#20


a = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
b = np.array([2, 1, 2])
mask = np.arange(3)[:,None] >= b
a[mask] = 0
a

array([[1, 2, 3],
       [4, 0, 6],
       [0, 0, 0]])

In [642]:
#21

ex21 = np.array([[[ 0, 1, 2, 3],
               [ 4, 5, 6, 7],
               [ 8, 9, 10, 11]],
              [[12, 13, 14, 15],
               [16, 17, 18, 19],
               [20, 21, 22, 23]]])
ex21[:,::2]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [20, 21, 22, 23]]])